"""Task 5 — real resolver -> Package nodes (resolve.py).

Unit tests use the FakeExecutor (from conftest) returning a canned ``uv pip
compile`` pinned closure.  No real uv/network/Docker is touched.

``resolve_closure`` takes ``roots`` as ``(import_id, dist_name)`` tuples (the
shape produced by ``naming.package_roots``) so it can emit Import->Package
``requires`` edges, and returns ``(list[Node], list[Edge])``.
"""

from __future__ import annotations

from python_deps.depgraph.executor import CommandResult
from python_deps.depgraph.resolve import UV_BIN, resolve_closure
from python_deps.depgraph.schema import (
    DiscoveredBy,
    Edge,
    EdgeType,
    Layer,
    NodeType,
    State,
)

# A realistic, annotated ``uv pip compile`` closure for roots opencv-python +
# Pillow.  numpy is a transitive dep of opencv-python (note the ``# via`` line);
# the roots themselves are annotated ``# via -r -`` (read from stdin).
CANNED_CLOSURE = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile - --python-version 3.11
numpy==1.26.4
    # via opencv-python
opencv-python==4.9.0.80
    # via -r -
Pillow==10.3.0
    # via -r -
"""

ROOTS = [("import:cv2", "opencv-python"), ("import:PIL", "Pillow")]


def _make_executor():
    # Imported lazily so the conftest sys.path shim is already applied.
    from conftest import FakeExecutor  # type: ignore

    return FakeExecutor(
        responses={
            "uv pip compile": CommandResult(
                command="uv pip compile",
                returncode=0,
                stdout=CANNED_CLOSURE,
                stderr="",
            )
        }
    )


def test_invokes_uv_pip_compile_with_expected_shape():
    ex = _make_executor()
    resolve_closure(ROOTS, ex)

    assert len(ex.calls) == 1, "exactly one resolver invocation expected"
    cmd = ex.calls[0]
    # Locked decision 1: the 'uv' binary, via 'uv pip compile'.
    assert UV_BIN in cmd
    assert "uv pip compile" in cmd
    # Both root distributions are fed to the resolver.
    assert "opencv-python" in cmd
    assert "Pillow" in cmd
    # Pinned to the requested interpreter.
    assert "--python-version" in cmd


def test_parses_pinned_lines_into_package_nodes():
    ex = _make_executor()
    nodes, _edges = resolve_closure(ROOTS, ex)

    by_name = {n.name: n for n in nodes}
    assert set(by_name) == {"opencv-python", "numpy", "Pillow"}

    cv = by_name["opencv-python"]
    assert cv.id == "pkg:opencv-python==4.9.0.80"
    assert cv.type is NodeType.PACKAGE
    assert cv.layer is Layer.PIP
    assert cv.discovered_by is DiscoveredBy.RESOLVER
    assert cv.version == "4.9.0.80"
    assert cv.state is State.UNKNOWN
    assert cv.check_command == "python -m pip show opencv-python"
    assert cv.fix_candidates == ("pip:opencv-python",)
    assert cv.chosen_fix == "pip:opencv-python"

    np = by_name["numpy"]
    assert np.version == "1.26.4"
    assert np.id == "pkg:numpy==1.26.4"
    assert np.check_command == "python -m pip show numpy"


def test_emits_import_to_package_requires_edges():
    ex = _make_executor()
    _nodes, edges = resolve_closure(ROOTS, ex)

    edge_set = {(e.src, e.dst) for e in edges}
    assert ("import:cv2", "pkg:opencv-python==4.9.0.80") in edge_set
    assert ("import:PIL", "pkg:Pillow==10.3.0") in edge_set

    for e in edges:
        assert isinstance(e, Edge)
        assert e.relation is EdgeType.REQUIRES
        assert e.origin == "resolver"


def test_emits_transitive_package_to_package_edges_from_annotations():
    ex = _make_executor()
    _nodes, edges = resolve_closure(ROOTS, ex)

    edge_set = {(e.src, e.dst) for e in edges}
    # numpy is "# via opencv-python" -> opencv-python requires numpy.
    assert ("pkg:opencv-python==4.9.0.80", "pkg:numpy==1.26.4") in edge_set
    # Roots themselves ("# via -r -") must NOT create spurious Package->Package
    # edges from a filename/stdin marker.
    assert not any(e.dst == "pkg:opencv-python==4.9.0.80" and e.src.startswith("pkg:") for e in edges)


def test_case_insensitive_dist_match_for_root_edges():
    # The resolver may normalize names; root edges must still resolve when the
    # declared dist name differs in case/separators from the pinned line.
    ex = _make_executor()
    roots = [("import:cv2", "OpenCV-Python")]
    _nodes, edges = resolve_closure(roots, ex)
    assert ("import:cv2", "pkg:opencv-python==4.9.0.80") in {
        (e.src, e.dst) for e in edges
    }


def test_compile_command_feeds_roots_via_heredoc_stdin():
    # Pin the command *shape*: roots are fed on stdin via a heredoc, not as argv.
    from python_deps.depgraph.resolve import _compile_command

    cmd = _compile_command(["opencv-python", "Pillow"], "3.11")
    assert "<<'DEPGRAPH_REQS'" in cmd
    # The roots appear in the heredoc body (each on its own line) ...
    body = cmd.split("<<'DEPGRAPH_REQS'\n", 1)[1]
    assert "opencv-python\nPillow" in body
    assert body.rstrip().endswith("DEPGRAPH_REQS")
    # ... and uv reads from stdin (the `-` source), not a requirements file.
    assert " - " in cmd


def test_no_annotation_closure_degrades_to_import_edges_only():
    # Locked decision 2 fallback: when uv emits NO `# via` annotations, we still
    # create Package nodes and Import->Package edges, but zero Package->Package.
    from conftest import FakeExecutor  # type: ignore

    flat = """\
numpy==1.26.4
opencv-python==4.9.0.80
Pillow==10.3.0
"""
    ex = FakeExecutor(
        responses={
            "uv pip compile": CommandResult(
                command="uv pip compile", returncode=0, stdout=flat, stderr=""
            )
        }
    )
    nodes, edges = resolve_closure(ROOTS, ex)

    assert {n.name for n in nodes} == {"numpy", "opencv-python", "Pillow"}
    edge_set = {(e.src, e.dst) for e in edges}
    # Import->Package still emitted.
    assert ("import:cv2", "pkg:opencv-python==4.9.0.80") in edge_set
    assert ("import:PIL", "pkg:Pillow==10.3.0") in edge_set
    # No Package->Package edges (no annotations to derive them from).
    assert not any(e.src.startswith("pkg:") for e in edges)


def test_parses_multiparent_via_continuation_lines():
    # A child with a multi-line `# via` block (parents on continuation lines)
    # must yield a Package->Package edge for EACH parent.
    from conftest import FakeExecutor  # type: ignore

    closure = """\
numpy==1.26.4
    # via
    #   opencv-python
    #   Pillow
opencv-python==4.9.0.80
    # via -r -
Pillow==10.3.0
    # via -r -
"""
    ex = FakeExecutor(
        responses={
            "uv pip compile": CommandResult(
                command="uv pip compile", returncode=0, stdout=closure, stderr=""
            )
        }
    )
    _nodes, edges = resolve_closure(ROOTS, ex)
    edge_set = {(e.src, e.dst) for e in edges}
    assert ("pkg:opencv-python==4.9.0.80", "pkg:numpy==1.26.4") in edge_set
    assert ("pkg:Pillow==10.3.0", "pkg:numpy==1.26.4") in edge_set


def test_resolver_failure_returns_empty():
    from conftest import FakeExecutor  # type: ignore

    ex = FakeExecutor(
        responses={
            "uv pip compile": CommandResult(
                command="uv pip compile",
                returncode=2,
                stdout="",
                stderr="error: no solution found",
            )
        }
    )
    nodes, edges = resolve_closure(ROOTS, ex)
    assert nodes == []
    assert edges == []
