"""Task 8 — end-to-end orchestrator (``build.py``).

``build_dep_graph`` wires the pipeline (scan -> map -> resolve -> seed -> install
-> probe -> certify) over a tiny fixture repo, driven entirely by a
``FakeExecutor`` (no Docker/network/uv).  The canned outputs below model a repo
that imports ``cv2`` (needs libGL.so.1), ``PIL`` (clean), and ``psycopg2`` (build
fails: pg_config missing), so the run exercises every node type:
Test / Import / Package / SystemLib / Tool.

Resolution is HOST-side and install/probe/certify are CONTAINER-side; the unit
test injects the SAME ``FakeExecutor`` for both (``host_executor=`` kwarg).

Native gaps here all reconcile with a resolver *prediction* (opencv-python and
psycopg2 are both in ``PACKAGE_TO_SYSTEM_DEPS``): the observed ``libGL.so.1`` /
``pg_config`` gaps merge into the predicted apt-keyed nodes ``syslib:libgl1`` /
``tool:libpq-dev`` (no duplicate soname/tool node), which therefore keep their
RESOLVER discovery origin while gaining the real check + a probe attempt.
"""

from __future__ import annotations

from python_deps.depgraph.build import build_dep_graph
from python_deps.depgraph.executor import CommandResult
from python_deps.depgraph.ids import (
    TEST_NODE_ID,
    import_id,
    package_id,
    syslib_id,
    tool_id,
)
from python_deps.depgraph.schema import DiscoveredBy, NodeType, State

CANNED_CLOSURE = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile - --python-version 3.11
numpy==1.26.4
    # via opencv-python
opencv-python==4.9.0.80
    # via -r -
Pillow==10.3.0
    # via -r -
psycopg2==2.9.9
    # via -r -
"""

INSTALL_STDERR = (
    "Building wheel for psycopg2 (setup.py): started\n"
    "    Error: pg_config executable not found.\n"
    "Building wheel for psycopg2 (setup.py): finished with status 'error'\n"
)


def _r(returncode=0, stdout="", stderr=""):
    return CommandResult(
        command="", returncode=returncode, stdout=stdout, stderr=stderr
    )


def _make_repo(tmp_path):
    (tmp_path / "app.py").write_text(
        "import os\nimport cv2\nfrom PIL import Image\nimport psycopg2\n"
    )
    return str(tmp_path)


def _make_executor():
    from conftest import FakeExecutor  # type: ignore

    return FakeExecutor(
        responses={
            "uv pip compile": _r(stdout=CANNED_CLOSURE),
            "pip install": _r(returncode=1, stderr=INSTALL_STDERR),
            # import probes (also reused by certification of the import nodes)
            "import cv2": _r(
                returncode=1,
                stderr="ImportError: libGL.so.1: cannot open shared object file",
            ),
            "import PIL": _r(returncode=0),
            "import psycopg2": _r(
                returncode=1, stderr="ModuleNotFoundError: No module named 'psycopg2'"
            ),
            "import numpy": _r(returncode=0),
            # package certification
            "pip show opencv-python": _r(returncode=0),
            "pip show numpy": _r(returncode=0),
            "pip show Pillow": _r(returncode=0),
            "pip show psycopg2": _r(returncode=1, stderr="WARNING: Package(s) not found"),
            # system / toolchain certification
            "ldconfig": _r(returncode=1),
            "command -v pg_config": _r(returncode=1),
            # goal
            "pytest": _r(returncode=1, stderr="tests failed"),
        }
    )


def _build(tmp_path):
    ex = _make_executor()
    return build_dep_graph(_make_repo(tmp_path), ex, host_executor=ex)


def test_build_produces_all_node_types(tmp_path):
    graph = _build(tmp_path)

    # Test goal node.
    assert graph.get(TEST_NODE_ID) is not None
    # Imports (stdlib ``os`` excluded).
    for name in ("cv2", "PIL", "psycopg2"):
        assert graph.get(import_id(name)) is not None
    assert graph.get(import_id("os")) is None
    # Packages from the resolver.
    assert graph.get(package_id("opencv-python", "4.9.0.80")) is not None
    assert graph.get(package_id("numpy", "1.26.4")) is not None
    assert graph.get(package_id("Pillow", "10.3.0")) is not None
    assert graph.get(package_id("psycopg2", "2.9.9")) is not None
    # SystemLib + Tool — the observed gaps reconcile into the apt-keyed
    # predictions (no duplicate soname/tool node is created).
    assert graph.get(syslib_id("libgl1")) is not None
    assert graph.get(tool_id("libpq-dev")) is not None
    assert graph.get(syslib_id("libGL.so.1")) is None
    assert graph.get(tool_id("pg_config")) is None


def test_build_requires_topology(tmp_path):
    graph = _build(tmp_path)

    edges = {(e.src, e.dst) for e in graph.edges}
    # Test -> Imports
    assert (TEST_NODE_ID, import_id("cv2")) in edges
    assert (TEST_NODE_ID, import_id("psycopg2")) in edges
    # Import -> Package
    assert (import_id("cv2"), package_id("opencv-python", "4.9.0.80")) in edges
    assert (import_id("PIL"), package_id("Pillow", "10.3.0")) in edges
    # Package -> Package (transitive, from uv annotation)
    assert (
        package_id("opencv-python", "4.9.0.80"),
        package_id("numpy", "1.26.4"),
    ) in edges
    # Package -> SystemLib / Tool (predicted at resolve, reconciled by probe)
    assert (
        package_id("opencv-python", "4.9.0.80"),
        syslib_id("libgl1"),
    ) in edges
    assert (package_id("psycopg2", "2.9.9"), tool_id("libpq-dev")) in edges


def test_build_certified_states(tmp_path):
    graph = _build(tmp_path)

    assert graph.get(package_id("opencv-python", "4.9.0.80")).state is State.SATISFIED
    assert graph.get(package_id("numpy", "1.26.4")).state is State.SATISFIED
    assert graph.get(package_id("Pillow", "10.3.0")).state is State.SATISFIED
    assert graph.get(package_id("psycopg2", "2.9.9")).state is State.MISSING

    assert graph.get(import_id("PIL")).state is State.SATISFIED
    assert graph.get(import_id("cv2")).state is State.MISSING
    assert graph.get(import_id("psycopg2")).state is State.MISSING

    assert graph.get(syslib_id("libgl1")).state is State.MISSING
    assert graph.get(tool_id("libpq-dev")).state is State.MISSING
    assert graph.get(TEST_NODE_ID).state is State.MISSING


def test_build_reconciled_predictions_keep_resolver_origin(tmp_path):
    graph = _build(tmp_path)

    libgl1 = graph.get(syslib_id("libgl1"))
    libpq = graph.get(tool_id("libpq-dev"))
    # discovery origin is preserved across reconciliation (spec: discovered_by
    # stays the discovery origin; only the certifier flips state).
    assert libgl1.discovered_by is DiscoveredBy.RESOLVER
    assert libpq.discovered_by is DiscoveredBy.RESOLVER
    # but the observed check + probe attempt prove the probe reconciled them.
    assert libgl1.check_command == "ldconfig -p | grep libGL.so.1"
    assert libpq.check_command == "command -v pg_config"
    assert libgl1.fix_candidates == ("apt:libgl1",)
    assert libpq.fix_candidates == ("apt:libpq-dev",)
    assert any(a.outcome == "failed" for a in libgl1.attempts)


def test_build_discovered_by_stamping(tmp_path):
    graph = _build(tmp_path)

    assert graph.get(import_id("cv2")).discovered_by is DiscoveredBy.STATIC_SCAN
    assert graph.get(TEST_NODE_ID).discovered_by is DiscoveredBy.GOAL
    assert (
        graph.get(package_id("numpy", "1.26.4")).discovered_by
        is DiscoveredBy.RESOLVER
    )


def test_build_discovered_cycle_per_stage(tmp_path):
    graph = _build(tmp_path)

    # stage 1 (scan): Test + Imports
    assert graph.get(TEST_NODE_ID).discovered_cycle == 1
    assert graph.get(import_id("cv2")).discovered_cycle == 1
    # stage 2 (resolver): Packages and predicted native nodes
    assert graph.get(package_id("numpy", "1.26.4")).discovered_cycle == 2
    # predicted-then-reconciled nodes keep the resolver discovery cycle (2)
    assert graph.get(syslib_id("libgl1")).discovered_cycle == 2
    assert graph.get(tool_id("libpq-dev")).discovered_cycle == 2


def test_build_empty_repo_yields_only_test_node(tmp_path):
    (tmp_path / "app.py").write_text("import os\nimport sys\n")
    from conftest import FakeExecutor  # type: ignore

    ex = FakeExecutor(default=_r(returncode=1, stderr="x"))
    graph = build_dep_graph(str(tmp_path), ex, host_executor=ex)

    assert graph.get(TEST_NODE_ID) is not None
    assert [n for n in graph.nodes if n.type is NodeType.IMPORT] == []
    assert [n for n in graph.nodes if n.type is NodeType.PACKAGE] == []


def test_project_node_hubs_runtime_deps_and_routes_test_deps(tmp_path):
    """Project node: runtime declared deps hang off Project; test/optional deps
    hang off the Test goal; certifi gains a parent (the no-parent observation)."""
    from python_deps.depgraph.build import _add_project_node
    from python_deps.depgraph.ids import project_id
    from python_deps.depgraph.schema import (
        DepGraph,
        DiscoveredBy,
        Edge,
        EdgeType,
        Layer,
        Node,
    )

    (tmp_path / "pyproject.toml").write_text(
        '[project]\n'
        'name = "myproj"\n'
        'dependencies = ["certifi>=2020"]\n'
        '[project.optional-dependencies]\n'
        'test = ["pytest>=7"]\n'
    )
    test_node = Node(
        id=TEST_NODE_ID, type=NodeType.TEST, name="repo_tests_pass",
        layer=Layer.TESTS, discovered_by=DiscoveredBy.GOAL,
    )
    certifi = Node(
        id=package_id("certifi", "2026.1.1"), type=NodeType.PACKAGE,
        name="certifi", version="2026.1.1", layer=Layer.PIP,
        discovered_by=DiscoveredBy.RESOLVER,
    )
    pytest_pkg = Node(
        id=package_id("pytest", "8.0.0"), type=NodeType.PACKAGE, name="pytest",
        version="8.0.0", layer=Layer.PIP, discovered_by=DiscoveredBy.RESOLVER,
    )
    graph = DepGraph().with_node(test_node).with_node(certifi).with_node(pytest_pkg)

    out = _add_project_node(graph, str(tmp_path))
    pid = project_id("myproj")

    proj = out.get(pid)
    assert proj is not None and proj.type is NodeType.PROJECT

    req = {(e.src, e.dst) for e in out.edges if e.relation is EdgeType.REQUIRES}
    assert (TEST_NODE_ID, pid) in req  # Test -> Project
    assert (pid, package_id("certifi", "2026.1.1")) in req  # runtime dep off Project
    assert (TEST_NODE_ID, package_id("pytest", "8.0.0")) in req  # test dep off Test
    # certifi now has a parent (no longer orphaned at the top of the layer)
    assert any(e.dst == package_id("certifi", "2026.1.1") for e in out.edges)
