"""Task 8 — end-to-end orchestrator (``build.py``).

``build_dep_graph`` wires stages 1->5 (scan -> map -> resolve -> seed -> install
-> probe -> certify) over a tiny fixture repo, driven entirely by a
``FakeExecutor`` (no Docker/network/uv).  The canned outputs below model a repo
that imports ``cv2`` (needs libGL.so.1), ``PIL`` (clean), and ``psycopg2`` (build
fails: pg_config missing), so the run exercises every node type:
Test / Import / Package / SystemLib / Tool.
"""

from __future__ import annotations

from python_deps.depgraph.build import build_dep_graph
from python_deps.depgraph.executor import CommandResult
from python_deps.depgraph.ids import (
    TEST_NODE_ID,
    import_id,
    package_id,
    syslib_id,
    tool_id,
)
from python_deps.depgraph.schema import DiscoveredBy, NodeType, State

CANNED_CLOSURE = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile - --python-version 3.11
numpy==1.26.4
    # via opencv-python
opencv-python==4.9.0.80
    # via -r -
Pillow==10.3.0
    # via -r -
psycopg2==2.9.9
    # via -r -
"""

INSTALL_STDERR = (
    "Building wheel for psycopg2 (setup.py): started\n"
    "    Error: pg_config executable not found.\n"
    "Building wheel for psycopg2 (setup.py): finished with status 'error'\n"
)


def _r(returncode=0, stdout="", stderr=""):
    return CommandResult(
        command="", returncode=returncode, stdout=stdout, stderr=stderr
    )


def _make_repo(tmp_path):
    (tmp_path / "app.py").write_text(
        "import os\nimport cv2\nfrom PIL import Image\nimport psycopg2\n"
    )
    return str(tmp_path)


def _make_executor():
    from conftest import FakeExecutor  # type: ignore

    return FakeExecutor(
        responses={
            "uv pip compile": _r(stdout=CANNED_CLOSURE),
            "pip install": _r(returncode=1, stderr=INSTALL_STDERR),
            # import probes (also reused by certification of the import nodes)
            "import cv2": _r(
                returncode=1,
                stderr="ImportError: libGL.so.1: cannot open shared object file",
            ),
            "import PIL": _r(returncode=0),
            "import psycopg2": _r(
                returncode=1, stderr="ModuleNotFoundError: No module named 'psycopg2'"
            ),
            "import numpy": _r(returncode=0),
            # package certification
            "pip show opencv-python": _r(returncode=0),
            "pip show numpy": _r(returncode=0),
            "pip show Pillow": _r(returncode=0),
            "pip show psycopg2": _r(returncode=1, stderr="WARNING: Package(s) not found"),
            # system / toolchain certification
            "ldconfig": _r(returncode=1),
            "command -v pg_config": _r(returncode=1),
            # goal
            "pytest": _r(returncode=1, stderr="tests failed"),
        }
    )


def test_build_produces_all_node_types(tmp_path):
    graph = build_dep_graph(_make_repo(tmp_path), _make_executor())

    # Test goal node.
    assert graph.get(TEST_NODE_ID) is not None
    # Imports (stdlib ``os`` excluded).
    for name in ("cv2", "PIL", "psycopg2"):
        assert graph.get(import_id(name)) is not None
    assert graph.get(import_id("os")) is None
    # Packages from the resolver.
    assert graph.get(package_id("opencv-python", "4.9.0.80")) is not None
    assert graph.get(package_id("numpy", "1.26.4")) is not None
    assert graph.get(package_id("Pillow", "10.3.0")) is not None
    assert graph.get(package_id("psycopg2", "2.9.9")) is not None
    # Probe-discovered SystemLib + Tool.
    assert graph.get(syslib_id("libGL.so.1")) is not None
    assert graph.get(tool_id("pg_config")) is not None


def test_build_requires_topology(tmp_path):
    graph = build_dep_graph(_make_repo(tmp_path), _make_executor())

    edges = {(e.src, e.dst) for e in graph.edges}
    # Test -> Imports
    assert (TEST_NODE_ID, import_id("cv2")) in edges
    assert (TEST_NODE_ID, import_id("psycopg2")) in edges
    # Import -> Package
    assert (import_id("cv2"), package_id("opencv-python", "4.9.0.80")) in edges
    assert (import_id("PIL"), package_id("Pillow", "10.3.0")) in edges
    # Package -> Package (transitive, from uv annotation)
    assert (
        package_id("opencv-python", "4.9.0.80"),
        package_id("numpy", "1.26.4"),
    ) in edges
    # Package -> SystemLib / Tool (probe)
    assert (
        package_id("opencv-python", "4.9.0.80"),
        syslib_id("libGL.so.1"),
    ) in edges
    assert (package_id("psycopg2", "2.9.9"), tool_id("pg_config")) in edges


def test_build_certified_states(tmp_path):
    graph = build_dep_graph(_make_repo(tmp_path), _make_executor())

    assert graph.get(package_id("opencv-python", "4.9.0.80")).state is State.SATISFIED
    assert graph.get(package_id("numpy", "1.26.4")).state is State.SATISFIED
    assert graph.get(package_id("Pillow", "10.3.0")).state is State.SATISFIED
    assert graph.get(package_id("psycopg2", "2.9.9")).state is State.MISSING

    assert graph.get(import_id("PIL")).state is State.SATISFIED
    assert graph.get(import_id("cv2")).state is State.MISSING
    assert graph.get(import_id("psycopg2")).state is State.MISSING

    assert graph.get(syslib_id("libGL.so.1")).state is State.MISSING
    assert graph.get(tool_id("pg_config")).state is State.MISSING
    assert graph.get(TEST_NODE_ID).state is State.MISSING


def test_build_discovered_by_stamping(tmp_path):
    graph = build_dep_graph(_make_repo(tmp_path), _make_executor())

    assert graph.get(import_id("cv2")).discovered_by is DiscoveredBy.STATIC_SCAN
    assert graph.get(TEST_NODE_ID).discovered_by is DiscoveredBy.GOAL
    assert (
        graph.get(package_id("numpy", "1.26.4")).discovered_by
        is DiscoveredBy.RESOLVER
    )
    assert graph.get(syslib_id("libGL.so.1")).discovered_by is DiscoveredBy.PROBE
    assert graph.get(tool_id("pg_config")).discovered_by is DiscoveredBy.PROBE


def test_build_discovered_cycle_per_stage(tmp_path):
    graph = build_dep_graph(_make_repo(tmp_path), _make_executor())

    # stage 1 (scan): Test + Imports
    assert graph.get(TEST_NODE_ID).discovered_cycle == 1
    assert graph.get(import_id("cv2")).discovered_cycle == 1
    # stage 2 (resolver): Packages
    assert graph.get(package_id("numpy", "1.26.4")).discovered_cycle == 2
    # stage 3 (probe): SystemLib + Tool
    assert graph.get(syslib_id("libGL.so.1")).discovered_cycle == 3
    assert graph.get(tool_id("pg_config")).discovered_cycle == 3


def test_build_empty_repo_yields_only_test_node(tmp_path):
    (tmp_path / "app.py").write_text("import os\nimport sys\n")
    from conftest import FakeExecutor  # type: ignore

    graph = build_dep_graph(
        str(tmp_path), FakeExecutor(default=_r(returncode=1, stderr="x"))
    )

    assert graph.get(TEST_NODE_ID) is not None
    assert [n for n in graph.nodes if n.type is NodeType.IMPORT] == []
    assert [n for n in graph.nodes if n.type is NodeType.PACKAGE] == []
